---
- name: Restore playbook.yml
  hosts: all
  tasks:
    # 1) /etc/ansible/facts.d 디렉토리 삭제 (file)
    # 2) 웹 서비스 종료 - httpd (service)
    # 3) 웹 패키지 삭제 - httpd (yum)
    - name: 디렉토리 생성
      file: 
        path: /etc/ansible/facts.d
        state: absent

    - name: 웹 서비스 종료
      service:
        name: httpd
        state: stopped
        enabled: no
      ignore_errors: yes        

    - name: 웹 패키지 삭제
      yum: 
        name: httpd
        state: absent
      ignore_errors: yes        
